[package]
name = "olmac116/cmdr-plus"
description = "Extensible command console for Roblox developers, updated for better performance, bug fixes, and more! "
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs"]
include = ["CHANGELOG.md", "Cmdr", "default.project.json", "LICENSE"]

[dependencies]
